feat: rename sql in db directory

diff --git a/.github/workflows/ESLint.yml b/.github/workflows/ESLint.yml
--- a/.github/workflows/ESLint.yml
+++ b/.github/workflows/ESLint.yml
@@ -38,19 +38,31 @@ jobs:
 
           echo "🏁🏁🏁🏁🏁 Lint backend 🤖"
           cd "${GITHUB_WORKSPACE}"/Codigo/backend || exit 2
-          npm run lint || fracaso=1
+          if ! npm run lint; then
+            echo "❌ Error en Lint backend 😢"
+            fracaso=1
+          fi
 
           echo "🏁🏁🏁🏁🏁 Build backend 🍇"
           cd "${GITHUB_WORKSPACE}"/Codigo/backend || exit 3
-          npm run build || fracaso=1
+          if ! npm run build; then
+            echo "❌ Error en Build backend 😞"
+            fracaso=1
+          fi
 
           echo "🏁🏁🏁🏁🏁 Lint frontend 🚀"
           cd "${GITHUB_WORKSPACE}"/Codigo/frontend || exit 4
-          npm run lint || fracaso=1
+          if ! npm run lint; then
+            echo "❌ Error en Lint frontend 😔"
+            fracaso=1
+          fi
 
           echo "🏁🏁🏁🏁🏁 Build frontend 🛠️"
           cd "${GITHUB_WORKSPACE}"/Codigo/frontend || exit 5
-          npm run build || fracaso=1
+          if ! npm run build; then
+            echo "❌ Error en Build frontend 😟"
+            fracaso=1
+          fi
 
           if [ ${fracaso} -eq 1 ]; then
             echo "Se encontraron errores en el código 😱"
diff --git a/.github/workflows/SQL.yml b/.github/workflows/SQL.yml
--- a/.github/workflows/SQL.yml
+++ b/.github/workflows/SQL.yml
@@ -37,13 +37,19 @@ jobs:
           fracaso=0
 
           echo "🏁🏁🏁🏁🏁 Lint SQL 🗄️"
-          npx -y sql-lint --driver mysql "${GITHUB_WORKSPACE}"/Codigo/**/*.sql || fracaso=1
+          if ! npx -y sql-lint --driver mysql "${GITHUB_WORKSPACE}"/Codigo/**/*.sql; then
+            echo "❌ Error en Lint SQL (sql-lint) 😟"
+            fracaso=1
+          fi
 
           echo "🏁🏁🏁🏁🏁 Validar carga en MariaDB 🦭"
 
           for sql_file in "${GITHUB_WORKSPACE}"/Codigo/**/*.sql; do
             echo "📄 Cargando $(basename "$sql_file")..."
-            mariadb --verbose -h 127.0.0.1 -u root -proot cultura < "$sql_file" || fracaso=1
+            if ! mariadb -h 127.0.0.1 -u root -proot cultura < "$sql_file"; then
+              echo "❌ Error al cargar $(basename "$sql_file") en MariaDB 😔"
+              fracaso=1
+            fi
             echo
           done
 
